### ISSUE TITLE
is it a pumpkin or a pineapple?

### ISSUE THREAD

**Issue by mrcisdaduntman** [FoundationGames/Automobility#13]
the pumpkin frame is called pineapple do you evan know what a pineapple looks like well here it i
![index](https://user-images.githubusercontent.com/111192911/184502256-0dfbceb1-dbc8-4d1d-8955-40cb9ee22226.jpg)
s

**Comment by gdude2002** [comment]
Nope, [it's a pumpkin named pineapple!](https://quiltmc.org/about/newcomer-guide/#:~:text=Pineapple%3F%20Isn%E2%80%99t%20that%20a%20pumpkin%3F)

**Comment by mrcisdaduntman** [comment]
just why

**Comment by gdude2002** [comment]
Why not?
