### ISSUE TITLE
Toggleable Dash Panel

### ISSUE THREAD

**Issue by SammyForReal** [FoundationGames/Automobility#14]
Hi, so there are Dash Panels. Pretty cool.

But I think they could be even cooler, if they have the ability, to be toggable with a redstone signal.

This way, it would be possible to build cups that open new ways after lets say 2 rounds. A player could even add more conditions to it using redstone.
And to give a little inspiration, in the racing games of from this red plumber is it also possible. (And depending on which mods are used too, you could do really advanced stuff) ^^

**Comment by FoundationGames** [comment]
Added in 0.4, thanks for the cool suggestion
