### ISSUE TITLE
1.19.2 port?

### ISSUE THREAD

**Issue by lostopkk** [FoundationGames/Automobility#17]

**Comment by samuelh2005** [comment]
This would be nice because this seems to be the only good road vehicle mod for Fabric
Edit:
It is also very similar to Mr Crayfish's vehicle mod for Forge, which makes me like this mod even better without even trying it (because it can't be used in 1.19.2).

**Comment by farsenfsd** [comment]
Agreed, a 1.19.2 port would be great-
