### ISSUE TITLE
[Forge 43.2.3/1.19.2] Crash in heavily modded game

### ISSUE THREAD

**Issue by neutralboolean** [FoundationGames/Automobility#28]
I'll admit that I have a lot of mods installed but this crash log only references Automobility and it doesn't occur when I disable Automobility.
I believe it's some bad interaction between this mod and Optifine (preview version 1.19.2 HD U I1 pre4. I know working with preview builds is risky but I figured I'd give the feedback.
[crashlog-automobility.txt](https://github.com/FoundationGames/Automobility/files/10368839/crashlog-automobility.txt)

**Comment by JadedChara** [comment]
I had that exact same error too! The only difference? No Optifine.

> I'll admit that I have a lot of mods installed but this crash log only references Automobility and it doesn't occur when I disable Automobility. I believe it's some bad interaction between this mod and Optifine (preview version 1.19.2 HD U I1 pre4. I know working with preview builds is risky but I figured I'd give the feedback. [crashlog-automobility.txt](https://github.com/FoundationGames/Automobility/files/10368839/crashlog-automobility.txt)

**Comment by SuspiciousMango** [comment]
I believe I have figured out the crux of this issue! Its related to Forge's "missing mod dependency" screen. I was having the same crash and was able to track down a line in the log file that one of my mod dependencies was outdated, and updating it removed the error. It looks like the Forge version of automobility doesn't play nice with that screen and instead just crashes the entire game. If you remove automobility, the missing dependency screen should pop up and tell you what mod(s) need to be updated, and once they're updated, you can add automobility back to your instance and things should work just fine!

Update: someone already explained what I did but much better on [this issue](https://github.com/FoundationGames/Automobility/issues/29) so go look at that for a better explanation
