### ISSUE TITLE
Client won't start

### ISSUE THREAD

**Issue by Pepijn-DB** [FoundationGames/Automobility#8]
![image](https://user-images.githubusercontent.com/62875389/183990287-11abea79-1a5f-4d20-9366-38b3b90f5c38.png)
So this is what i see when im trying to start it

Bug or nah?

Log:
[latest.log](https://github.com/FoundationGames/Automobility/files/9303045/latest.log)

**Comment by FoundationGames** [comment]
See if the issue occurs with only Automobility and QSL installed 
(the log shows evidence of an error, however automobility shouldn't touch the part of the code that caused the error)

**Comment by Pepijn-DB** [comment]
That fixed it, thnx

**Comment by Mikm159** [comment]
Can you tell me how you solved this problem? I seem to be in the same situation.

> That fixed it, thnx

**Comment by CoreBytee** [comment]
Do you have the Create mod for fabric installed?
@Mikm159

**Comment by Pepijn-DB** [comment]
> Can you tell me how you solved this problem? I seem to be in the same situation.
> 
> 
> 
> > That fixed it, thnx
> 
> 
> 
> 

Just ran QLS and automobility

**Comment by Mikm159** [comment]
Yes,I guess the question comes from Myron. In fact, Create is not very compatible with Myron. I just found that this mod uses Myron.

> Do you have the Create mod for fabric installed? @Mikm159
